### ISSUE TITLE
special chars in payment note

### ISSUE THREAD

**Issue by j4ckse7en** [Tron-Europe-DevTeam/Gambio-TronBlockchainConnector#10]
If you insert a special char in the payment note there is a display error in the backend and the automatic assignment to a bill does not wiork.

![screen shot 2018-09-21 at 14 24 57](https://user-images.githubusercontent.com/14785062/45881006-248b5080-bdaa-11e8-91ec-842688edc12a.png)

**Comment by PMD3VSolution** [comment]
fixed
![grafik](https://user-images.githubusercontent.com/39301026/45886447-77b8cf80-bdb9-11e8-93df-c90b8e4515f3.png)
