### ISSUE TITLE
FRQ - tables search bar for orders

### ISSUE THREAD

**Issue by Tron-Europe-DevTeam** [Tron-Europe-DevTeam/Gambio-TronBlockchainConnector#3]
Feature-Request
-----------
add a search function to the table
- tables paging (50 entries)

![grafik](https://user-images.githubusercontent.com/43116595/45597728-bcff8a80-b9d0-11e8-82f0-d773ebff0a84.png)

Browser
-------
Google Chrome Version 66.0.3359.139
FireFox 59.0.3 
IE 11

**Comment by PMD3VSolution** [comment]
done! #15
